### PR TITLE
Simplify and modernize Base62

### PR DESCRIPTION
**Pull request by lassebunk**
Hi JT,

I have made some modifications to simplify the gem and modernize it.

I made the following:
- Simplify gemspec, e.g. using git to list files
- Use Bundler for development dependencies, so you can just run `bundle` to install dependencies when developing. This also adds some gem tasks like `rake release` to git tag version and release to RubyGems in one go.
- Add a Rakefile, so you can run `rake test`, or just `rake` to run tests. This also enables testing with Travis CI.
- Simplify the tests to make them easier to read
- Separate and simplify encoding and decoding to ensure code (`PRIMITIVES`) are only written once
- And finally simplify and convert all text files to markdown, because this appears to be more widely used for gems today.

Hope you can use it. Please let me know if you need anything else.

Thanks,
/Lasse

### CODE REVIEW

**Comment by lassebunk** [comment]
Hi @jtzemp .. You think this is interesting or not usable?

Thanks,
/Lasse

**Comment by jtzemp** [comment]
Hey, Lasse.

Thanks taking the time to refactor the code. Sorry I haven't had time to
look at it yet. I'll check it out soon. I'm sure it's great stuff. The most
important consideration for me is whether it passes the tests and doesn't
change the API w/o bumping the version number.

Thanks!

**Comment by lassebunk** [comment]
Super :) The API is the same.

**Comment by jordanyee** [comment]
Hi @jtzemp,

For what it's worth, I've taken a look through @lassebunk's code, run it against his new simplified tests and the original tests and it all works as it should. And the Markdown-formatted Readme is very welcome.

All the best,
Jordan

**Comment by jtzemp** [comment]
@jordanyee thanks for the cross check and the prompt to look at it again. With the holidays and all, I kind of fell off the planet.

@lassebunk thanks for being so patient.

**Comment by lassebunk** [comment]
@jtzemp No problem :) The gem was fine, mine was just adjustments.

**Comment by jordanyee** [comment]
@jtzemp No problem, I know what that's like! Welcome back : )

**Pull request merged**
